- hosts: linux
  become: yes
  tasks:
  - name: Instalando o Apache
    package:
      name: apache2
      state: present
  - name: Garantindo inicialização do Apache
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Garantindo o site
    copy:
      src: /home/ronygullity/site/jogo-da-memoria/
      dest: /var/www/html